### ISSUE TITLE
basic walkthrough of profiling techniques

### ISSUE THREAD

**Issue by jasonswearingen** [keijiro/BurstTestbed#1]
Could you link to, or somehow describe the minimal steps to profile/show the performance benefit    The screenshot in the project root folder shows some unity profiler tools, but it would be great to explain this a little bit.

**Comment by jasonswearingen** [comment]
fyi I am new to Unity, but a basic IL2CPP compile with unity's built-in profiler shows the following timings:

NoiseTexture.Update() timings:
Burst Enabled (this code):  18.5ms
Burst Disabled:  97ms 
Burst Enabled, Inline Unsafe: 16.8ms

The "Burst Enabled, Inline Unsafe" was done by passing the texture directly (as a NativeArray<Uint>) via a uint*.  main code rewritten to:

```c#
    [BurstCompile]
    public unsafe static void FillTexturePtrInline(float time, int _size, uint* buffer)
    {
        var offs = 0;

        for (var y = 0; y < _size; y++)
            for (var x = 0; x < _size; x++)
            {
                //buffer[offs++] = TextureGenerator.GetPixel(x, y, time);
                var pos = math.float3(x, y, time) * math.float3(0.008f, 0.008f, 0.5f);
                var f32 = noise.snoise(pos) * 0.4f + 0.5f;
                var un8 = (uint)(math.saturate(f32) * 255);
                buffer[offs++] = un8 | un8 << 8 | un8 << 16 | 0xff000000;
            }
    }
```

I am surprised that the "Inline Unsafe" is only slightly faster.  putting the loop in the burst function seems to have no effect.  Basically this is saying don't bother with unsafe.

PS:  something I learned:   "using" the NativeArray disposes it at the end of the function.

**Comment by keijiro** [comment]
I didn't do serious benchmarking because I should use the [C# Job System](https://docs.unity3d.com/Manual/JobSystem.html) if I consider performance. I just checked if it runs at a practical speed.

I think there is no documentation about performance since the direct call feature hasn't been finalized yet.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by jasonswearingen** [comment]
okay thank you for the followup.
